version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456Sr
    ports:
      - "5500:5432"

